version: "3"

services:
  signaler:
    build: ./signaler
    ports:
      - "5001:443"
    volumes:
      - ./signaler:/usr/local/src/github.com/pion/demo-conference/signaler
  www:
    build: ./www
    ports:
      - "5000:443"
    volumes:
      - ./www:/usr/local/src/github.com/pion/demo-conference/www
