version: "3"

services:
  signaler:
    build: ./signaler
    ports:
      - "5001:443"
    volumes:
      - ./signaler:/usr/local/src/github.com/pion/demo-conference/signaler
  frontend:
    build: ./frontend
    ports:
      - "5000:443"
